### ISSUE TITLE
copy link action takes too long 

### ISSUE THREAD

**Issue by axaluss** [ben-gibson/GitLink#202]
I disabled "Check commit on remote". The copy link action is still taking too long.

**Comment by ben-gibson** [comment]
How long does it take? How long does it take if you run the command `git ls-remote --heads` on your repo from the CLI?

**Comment by danielleontiev** [comment]
I have the issue to. I'd disabled checkbox but it have not changed the behaviour.

Running

```sh
git ls-remote --heads
```

is very slow too and it takes comparable amout of time as `Copy URL` in GitLink

**Comment by ben-gibson** [comment]
In most cases, in large repositories, it's checking the commit exists on the remote that's slow, however, it looks like this can also be the case for branches (presumably when the remote has a lots of branches to search through?)

I think we need two options in the plugin settings to solve this

* Check commit on remote (exists already)
* Check branch on remote (does not exist)

If both options are disabled, we don't check anything on the remote and just assume the commit or branch exists there (if it doesn't, the generated URL will lead to a 404).

Alternatively, perhaps we just need to check if a remote-tracking branch exists for the checked out branch and not use `git ls-remote --heads` at all 🤔.

Ideally, we'd also have new options to specify how GitLink generates a URL to the current file as mentioned in https://github.com/ben-gibson/GitLink/issues/190 i.e.

* Auto (prefers the commit if on remote, using the branch otherwise).
* Use commit (may result in a `404` if the commit is not on the remote)
* Use branch (may result in a `404` if the branch is not on the remote)

**Comment by danielleontiev** [comment]
> presumably when the remote has a lots of branches to search through?

Yes, now `git ls-remote --heads | wc -l` shows ~900 for me.

Personally, I would prefer to not check remotes at all - I use the plugin extensiveley and have never faced 404 issue. Having two checkboxes looks like the valid solution imo

**Comment by ben-gibson** [comment]
Yeah, having an option in the plugin settings to disable any `commit` or `branch` remote checks is definitely on the cards. Hopefully in the next few weeks.

**Comment by kang8** [comment]
👌🏽, wait for me to learn how to use kotlin to write jetbrain plugin.

**Comment by ben-gibson** [comment]
I've opted to change the existing setting `Check commit on remote` to a more general `Check remote` option that disables all checks on the remote (commit and branch). I think that aligns with the desired behaviour, which is, on large repositories to avoid the performance cost of a remote check. #251

**Comment by ben-gibson** [comment]
This should now be working in the latest version 4.2.2
