### ISSUE TITLE
Leading slash in {file:path} breaks links

### ISSUE THREAD

**Issue by sshnaidm** [ben-gibson/GitLink#216]
I set up GitLink for Gerrit gitweb, but filepath has a leading slash which gitweb doesn't handle and fails to open the page.
My config is: 
`https://mygerrithost/gerrit/gitweb?p=reponame.git;a=blob;f={file:path}/{file:name};hb={commit}#l{line:start}`
What is generated: 
`https://mygerrithost/gerrit/gitweb?p=reponame.git;a=blob;f=/folder/script.sh;hb=21df4d272fb1e577757e394d6bf3efcc853cdcf9#l39`
I would expect `f=folder/script.sh` instead of `f=/folder/script.sh`, without added leading slash.

**Comment by ben-gibson** [comment]
This should be fixed in `4.1.6`

**Comment by ben-gibson** [comment]
If you manage to create working templates for `Gerrit`, and you're happy to share them, I can add this as a host supported out of the box so other people can use it too.

**Comment by sshnaidm** [comment]
Gerrit doesn't have git UI, it uses [Gitweb](https://gerrit-documentation.storage.googleapis.com/Documentation/2.12/config-gitweb.html) instead. So my settings are for Gerrit-Gitweb setup:

Domain: `https://mygerrithost.com/gerrit/repo_name`
File at branch template: `https://mygerrithost.com/gerrit/gitweb?p=repo_name.git;a=blob;f={file:path}/{file:name};hb=refs/heads/{branch}#l{line:start}`
File at commit template: `https://mygerrithost.com/gerrit/gitweb?p=repo_name.git;a=blob;f={file:path}/{file:name};hb={commit}#l{line:start}`
Commit template: `https://mygerrithost.com/gerrit/gitweb?p=repo_name.git;a=commit;h={commit}`

Although I can't open file in commit template, it always tries to open `main` branch. Which doesn't exist in my case, so it's ending up with `404` error. Is there a way to define a "default" branch?

**Comment by ben-gibson** [comment]
Yeah, you can change the default branch from the main plugin settings. 

By default, it should use the commit template when opening a file, unless, the commit doesn't exist on the remote, either because it hasn't been pushed to the remote yet, or the `check commit on remote` option has been disabled, in which case, GitLink can't tell if the commit is on the remote. 

In that situation, it falls back to using the branch template with the currently checked-out branch. If that doesn't exist on the remote, then it uses the default branch defined in the plugin's project settings.

**Comment by sshnaidm** [comment]
Oops, sorry, option "check commit on remote" was really disabled. Now all works fine, thanks!
