### ISSUE TITLE
Decrease update frequency

### ISSUE THREAD

**Issue by dragetd** [ben-gibson/GitLink#222]
Hey there,

the automatic pipeline to release the plugin is really cool! Of course, it has the effect, that there are many update in the last weeks. At somehow it is a bit irritating to see the plugin updated sometimes multiple times a week.

Maybe the release CI could run a bit less often? Every one or two weeks?

Or maybe it is just me and I am silly, then feel free to close this issue. :)

**Comment by ben-gibson** [comment]
The pipeline doesn't automatically release new changes. A release is prepared, and updated when new commits are merged into the main branch, but each release still requires manual input to decide when it should be released and what changes it should include etc.

I think there was a flurry of updates after the major releases (4.0.0) and (4.1.0), but since then, the time between the last two updates has been 17 days.

I don't think it would be beneficial to limit the frequency of releases, sometimes there maybe more than one release in a given day and sometimes there may be weeks without any, it really just depends on a number of factors like feature requests, bugs, availability etc

Perhaps, just removing the notification when an update has been applied is all that's really needed, to make it a more silent process, unless something major has changed that should be made clear in the notification.
