### ISSUE TITLE
Go the reverse way

### ISSUE THREAD

**Issue by theScrabi** [ben-gibson/GitLink#64]
It would also be awsome if you could go the reverse way, and open a link from github in idea, so going from the website to the editor.

**Comment by SemanticBeeng** [comment]
This would be extremely useful in order to create live documentation by embedding copied code links into blogs, books, etc.

One difficulty I can see is ensuring project is on the right branch when navigating.
Living with the simplifying assumption that it is, what would it take @ben-gibson, please ?
