### ISSUE TITLE
Support for {remote-path} or {project} variables for custom host

### ISSUE THREAD

**Issue by joshkaplan** [ben-gibson/GitLink#91]
Saw this mentioned in a few old issues, but was never directly addressed: is it possible to add the a variable for {project} or {remote-path} variables for custom hosts? The use-case is when there are multiple VCS roots within a project

**Comment by ben-gibson** [comment]
Yep, there has definitely been a few requests for this so it's something I want to get added soon. Though I'm not sure this helps in cases where there are multi VCS roots in the same project. If all the roots are from the same host e.g. `GitHub` then it will work out of the box just by selecting `GitHub` as the host. If the VCS roots come from multiple hosts then even using the custom host won't help because you can't define a different URL structure on a per root basis.

**Comment by ben-gibson** [comment]
Moved into #92
